"""Assemble the master report from authored sections and pipeline tables.

Sections are hand-written prose under `sections/`; tables are generated by the
harvest pipeline. This script joins them in the order the brief specifies and
resolves placeholders, so the report can be rebuilt whenever the evidence is
refreshed without re-editing prose.

Placeholders inside section files:
    <!-- TABLE: literature -->   <!-- TABLE: patents -->
    <!-- TABLE: coverage -->     <!-- COUNT: originals -->
An unresolved placeholder is a build failure, not a silent gap.
"""
from __future__ import annotations

import csv
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SECTIONS = os.path.join(HERE, "sections")
TABLES = os.path.join(HERE, "tables")
OUT = os.path.join(HERE, "1-MCP-research-report.md")
ARTIFACTS = os.path.join(REPO, "outputs", "1mcp")

# The brief's required order. Section files are matched by numeric prefix.
ORDER = [
    "01_executive_conclusion", "02_novelty_correction", "03_methodology",
    "04_literature_table", "05_commercial", "06_patent_landscape",
    "07_compatibility", "07b_antimicrobial_selection", "08_architecture_matrix",
    "09_recommended_architecture", "10_formulation_manufacturing",
    "11_release_kinetics", "12_characterization", "13_produce_experiment",
    "14_regulatory", "15_technoeconomic", "16_failure_modes",
    "17_patent_evidence", "18_roadmap", "19_open_questions", "20_references",
]


def read(path: str) -> str:
    if not os.path.exists(path):
        return ""
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def load_counts() -> dict:
    path = os.path.join(ARTIFACTS, "20_verification.json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def md_from_csv(path: str, columns: list[str] | None = None, limit: int | None = None) -> str:
    if not os.path.exists(path):
        return "_Table not yet generated — run the harvest pipeline._"
    with open(path, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        return "_No rows._"
    cols = columns or list(rows[0].keys())
    if limit:
        rows = rows[:limit]

    def cell(v: object) -> str:
        s = " ".join(str(v or "").split()).replace("|", "\\|")
        return s or "—"

    out = ["| " + " | ".join(cols) + " |",
           "| " + " | ".join("---" for _ in cols) + " |"]
    out += ["| " + " | ".join(cell(r.get(c)) for c in cols) + " |" for r in rows]
    return "\n".join(out)


def reference_list() -> str:
    """Numbered references built only from verified pipeline output.

    Nothing is added by hand: if a work is not in the harvested corpus with a
    Crossref-resolved DOI, it does not appear here.
    """
    lit = os.path.join(TABLES, "literature.csv")
    pat = os.path.join(TABLES, "patents.csv")
    out: list[str] = []

    if os.path.exists(lit):
        with open(lit, encoding="utf-8", newline="") as fh:
            rows = list(csv.DictReader(fh))
        rows.sort(key=lambda r: (r.get("reference") or "").lower())
        out.append(f"## Peer-reviewed sources ({len(rows)})\n")
        for i, r in enumerate(rows, 1):
            ref = " ".join((r.get("reference") or "").split())
            doi = (r.get("doi") or "").strip()
            kind = (r.get("pub_type") or "").replace("_", " ")
            ft = "full text retrieved" if r.get("fulltext_chars") not in ("", "0", None) \
                else "abstract only"
            line = f"{i}. {ref}"
            if doi:
                line += f" https://doi.org/{doi}"
            line += f" *[{kind}; {ft}]*"
            out.append(line)
        out.append("")

    if os.path.exists(pat):
        with open(pat, encoding="utf-8", newline="") as fh:
            prows = list(csv.DictReader(fh))
        prows.sort(key=lambda r: (r.get("priority_date") or "9999"))
        out.append(f"## Patent documents ({len(prows)} families)\n")
        for i, r in enumerate(prows, 1):
            num = r.get("pub_number") or ""
            title = " ".join((r.get("title") or "").split())
            asg = " ".join((r.get("assignee") or "").split())
            pri = r.get("priority_date") or "priority date not established"
            line = f"{i}. **{num}** — {title or '[title not established]'}"
            if asg:
                line += f" ({asg})"
            line += f". Priority: {pri}. https://patents.google.com/patent/{num}/en"
            out.append(line)
        out.append("")

    return "\n".join(out) if out else "_References not yet generated._"


def resolve(text: str, counts: dict) -> tuple[str, list[str]]:
    unresolved: list[str] = []

    def table_sub(m: re.Match) -> str:
        name = m.group(1).strip()
        path = os.path.join(TABLES, f"{name}.csv")
        if name == "coverage":
            path = os.path.join(ARTIFACTS, "20_coverage.csv")
        if not os.path.exists(path):
            unresolved.append(f"TABLE:{name}")
            return f"_[unresolved table: {name}]_"
        return md_from_csv(path)

    def count_sub(m: re.Match) -> str:
        key = m.group(1).strip()
        if key not in counts:
            unresolved.append(f"COUNT:{key}")
            return f"_[unresolved count: {key}]_"
        return str(counts[key])

    text = re.sub(r"<!--\s*TABLE:\s*([\w-]+)\s*-->", table_sub, text)
    text = re.sub(r"<!--\s*COUNT:\s*([\w-]+)\s*-->", count_sub, text)
    text = re.sub(r"<!--\s*REFERENCES\s*-->", lambda _m: reference_list(), text)
    return text, unresolved


def main() -> int:
    counts = load_counts()
    parts = [
        "# Humidity-responsive controlled-release 1-MCP packaging",
        "",
        "### A literature, technology, commercial and patent-landscape assessment",
        "",
        "> **Scope and limits.** Every value in the evidence tables is traceable to a "
        "quote in a document that was actually retrieved; values that could not be "
        "verified are marked, never guessed. This report expresses **no freedom-to-"
        "operate or patentability opinion** — those require claim-by-claim review by "
        "qualified counsel. Proposed formulations are labelled as experimental "
        "hypotheses, not literature-established facts.",
        "",
        "---",
        "",
    ]

    missing_sections: list[str] = []
    all_unresolved: list[str] = []
    for name in ORDER:
        path = os.path.join(SECTIONS, f"{name}.md")
        body = read(path)
        if not body.strip():
            missing_sections.append(name)
            continue
        body, unresolved = resolve(body, counts)
        all_unresolved += unresolved
        parts.append(body.rstrip())
        parts.append("\n---\n")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts).rstrip() + "\n")

    words = len(" ".join(parts).split())
    print(f"wrote {OUT}")
    print(f"  sections: {len(ORDER) - len(missing_sections)}/{len(ORDER)}  (~{words:,} words)")
    if missing_sections:
        print(f"  MISSING: {', '.join(missing_sections)}")
    if all_unresolved:
        print(f"  UNRESOLVED PLACEHOLDERS: {', '.join(sorted(set(all_unresolved)))}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
